---
# tasks file for update-system-macos
- name: Update & Upgrade Homebrew Packages
  homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Upgrade Homebrew Cask Packages
  homebrew_cask:
    upgrade_all: true
    greedy: true
    install_options: "no-quarantine"
    sudo_password: ansible_become_password
  register: cask_status
  changed_when: cask_status['msg'] != 'Homebrew casks upgraded.'

- name: Mas check for outdated apps
  command:
    cmd: mas outdated
  register: mas_outdated
  changed_when: mas_outdated.stderr != ''
  notify: Upgrade macOS Apps
  environment:
    PATH: "/opt/homebrew/bin/:/usr/local/bin/:{{ ansible_env.PATH }}"

- name: Check for macOS system updates
  become: true
  command:
    cmd: softwareupdate --list
  register: macos_outdated
  changed_when: "'No new software available.' not in macos_outdated.stderr"
  notify: Install macOS System Updates
