---
# handlers file for update-system-macos
- name: Upgrade macOS Apps
  command:
    cmd: mas upgrade

- name: Install macOS System Updates
  debug:
    msg: "macOS system updates are avialable. Please update locally."
