---
# handlers file for update-system-macos
- name: Upgrade macOS Apps
  command:
    cmd: mas upgrade
  environment:
    PATH: "/opt/homebrew/bin/:/usr/local/bin/:{{ ansible_env.PATH }}"

- name: Install macOS System Updates
  debug:
    msg: "macOS system updates are avialable. Please update locally."
