---
# handlers file for update-system-macos
- name: Upgrade macOS Apps
  command:
    cmd: mas upgrade

- name: Install macos System Updates
  become: true
  command:
    stdin: "{{ ansible_become_password }}"
    cmd: softwareupdate --install --all --restart --stdinpass
