---
# handlers file for update-system-macos
- name: Upgrade macOS Apps
  command:
    cmd: mas upgrade

- name: Install macos System Updates
  become: true
  command:
    stdin: "{{}}"
    cmd: softwareupdate --install --all --restart --stdinpass
  vars:
    ansible_become_password: "{{ sudo_pass }}"
